
[[boundary]]
=== boundary

set that represents the limit of an entity

NOTE: Boundary is most commonly used in the context of geometry, where the set is a collection of points or a collection of objects
that represent those points. In other domains, the term is used metaphorically to describe the transition between an entity and the rest of its domain of discourse.

[.source]
<<ISO19107-2019,clause 3.6>>

[[cell]]
=== cell

<DGGS> spatial, spatio-temporal or temporal unit of geometry with dimension greater than 0, associated with a zone (<<zone>>)

NOTE: All cells within a DGGS (<<dggs>>) share the dimensionality of the DGGS's parent global (<<globe>>) geometry. DGGS with dimensionality of 0, are not supported.

NOTE: Cells are the unit of geometry in a DGGS, and the geometry of the region of space-time occupied by a zone is a cell.

NOTE: While the terms cell and zone are often used interchangeably, strictly zone is the preferred term. Cell is entirely appropriate when specifically discussing a zone's geometry or topology.

[[cell_refinement]]
=== cell refinement

<DGGS> process of subdividing _parent cells_ (<<parent_cell>>) into descendant _child cells_ (<<child_cell>>) using a specified _refinement ratio_ (<<refinement_ratio>>) and suite of refinement strategies

NOTE: Iterative application of cell refinements creates a hierarchy of descendant _discrete global grids_ (<<discrete_global_grid>>).

NOTE: Cell refinement methods may result in child cells that each have a single parent or that have multiple parents.

[[child_cell]]
=== child cell
alt:[child]

<DGGS> immediate descendant of a _parent cell_ (<<parent_cell>>)

NOTE: Child cells are either within a single parent cell or overlapped by multiple parent cells

[[class]]
=== class

description of a set of objects that share the same attributes, operations, methods, relationships, and semantics

NOTE: A class may use a set of interfaces to specify collections of operations it provides to its environment.
The term was first used in this way in the general theory of object-oriented programming, and later adopted for use in this same sense in UML.

[.source]
<<ISO19103,clause 4.7>>, Note 1 to entry has been added from <<ISO19117-2012,clause 4.2>>

[[compound_coordinate_reference_system]]
=== compound coordinate reference system
alt:[compound CRS]

_coordinate reference system_ (<<coordinate_reference_system>>) using at least two independent coordinate reference systems

NOTE: Coordinate reference systems are independent of each other if coordinate values
in one cannot be converted or transformed into coordinate values in the other.

[.source]
<<ISO19111-2019,clause 3.1.3>>

[[coordinate_reference_system]]
=== coordinate reference system
alt:[CRS]

coordinate system that is related to an object by a _datum_ (<<datum>>)

NOTE: Geodetic and vertical datums are referred to as reference frames.

NOTE: For geodetic and vertical datums, the object will be the Earth.
In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.

[.source]
<<ISO19111-2019,clause 3.1.9>>

[[coordinate_system]]
=== coordinate system

set of mathematical rules for specifying how coordinates are to be assigned to points

[.source]
<<ISO19111-2019,clause 3.1.11>>

[[data_type]]
=== data type

specification of a _value_ (<<value>>) domain with operations allowed on values in this domain

[example]
Integer, Real, Boolean, String, Date (conversion of a date into a series of codes).

NOTE: Data types include primitive predefined types and user-definable types. All instances of a data type lack identity.

[.source]
<<ISO19103,clause 4.14>>, Note 1 to entry has been added from <<ISO19156-2011,clause 4.3>>

[[datum]]
=== datum
alt:[reference frame]

parameter or set of parameters that realize the positions of the origin, the scale, and the orientation of a _coordinate system_ (<<coordinate_system>>)

[.source]
<<ISO19111-2019,clause 3.1.15>>

[[datum_ensemble]]
=== datum ensemble

group of multiple realizations of the same terrestrial or vertical reference system that, for approximate spatial referencing purposes, are not significantly different

NOTE: Datasets referenced to the different realizations within a datum ensemble may be merged without coordinate transformation.

NOTE:  ‘Approximate’ is for users to define but typically is in the order of under 1 decimetre but may be up to 2 metres.

[example]
“WGS 84” as an undifferentiated group of realizations including WGS 84 (TRANSIT), WGS 84 (G730), WGS 84 (G873), WGS 84 (G1150), WGS 84 (G1674) and WGS 84 (G1762).
At the surface of the Earth these have changed on average by 0.7 m between the TRANSIT and G730 realizations,
a further 0.2 m between G730 and G873, 0.06 m between G873 and G1150, 0.2 m between G1150 and G1674 and 0.02 m between G1674 and G1762).

[.source]
<<ISO19111-2019,clause 3.1.16>>

[[discrete_global_grid]]
=== discrete global grid

<DGGS> set of _cells_ (<<cell>>) at the same _refinement level_ (<<refinement_level>>), that uniquely and completely cover a _globe_ (<<globe>>)

NOTE: the set of cell _zonal identifiers_ (<<zonal_identifier>>) comprising a discrete global grid form a single Zone Class with its associated refinement level.

NOTE: the configuration of the set of cells comprising a discrete global grid satisfy at least one grid constraint in the DGG_GridConstraint codelist.

[[dggs]]
=== discrete global grid system
alt:[DGGS]

integrated system comprising a _hierarchy_ (<<hierarchy>>) of _discrete global grids_ (<<discrete_global_grid>>), _spatio-temporal referencing_ (<<spatio-temporal_reference>>) by _zonal identifiers_ (<<zonal_identifier>>) and functions for _quantization_ (<<quantization>>),
_zonal query_ (<<zonal_query>>), and _interoperability_ (<<interoperability>>)

[[duration]]
=== duration

non-negative quantity of time equal to the difference between the final and initial _instants_ (<<instant>>) of a time _interval_ (<<interval>>)

NOTE: The duration is one of the base quantities in the International System of Quantities (ISQ) on which the International System of Units (SI) is based.
The term “time” instead of “duration” is often used in this context and also for an infinitesimal duration.

NOTE: For the term “duration”, expressions such as “time” or “time interval” are often used,
but the term “time” is not recommended in this sense and the term “time interval” is deprecated in this sense to avoid confusion with the concept of “time interval”.

NOTE: The exact duration of a time scale unit depends on the time scale used.
For example, the durations of a year, month, week, day, hour or minute, may depend on when they occur
[in a Gregorian calendar, a calendar month can have a duration of 28, 29, 30, or 31 days; in a 24-hour clock, a clock minute can have a duration of 59, 60, or 61 seconds, etc.].
Therefore, the exact duration can only be evaluated if the exact duration of each is known.

NOTE: This definition is closely related to NOTE 1 of the terminological entry “duration” in IEC 60050-113:2011, 113-01-13.

[.source]
<<ISO8601-1-2019,clause 3.1.1.8>>

[[dynamic_coordinate_reference_system]]
=== dynamic coordinate reference system
alt:[dynamic CRS]

_coordinate reference system_ (<<coordinate_reference_system>>) that has a _dynamic reference frame_ (<<dynamic_reference_frame>>)

NOTE: Coordinates of points on or near the crust of the Earth that are referenced to a dynamic coordinate reference system may change with time,
usually due to crustal deformations such as tectonic motion and glacial isostatic adjustment.

NOTE: Metadata for a dataset referenced to a dynamic coordinate reference system should include coordinate epoch information.

[.source]
<<ISO19111-2019,clause 3.1.19>>

[[dynamic_reference_frame]]
=== dynamic reference frame
alt:[dynamic datum]

_reference frame_ (<<datum>>) in which the defining parameters include time evolution

NOTE: The defining parameters that have time evolution are usually a coordinate set.

[.source]
<<ISO19111-2019,clause 3.1.20>>

[[error_budget]]
=== error budget

<metric> statement of or methodology for describing the nature and magnitude of the errors which affect the results of a calculation

[.source]
<<ISO19107-2019, clause 3.35>>, Note 1 to entry has been removed

[[feature]]
=== feature

abstraction of real-world phenomena

NOTE: A feature can occur as a type or an instance. In this document, feature instance is meant unless otherwise specified.

[.source]
<<ISO19101-1,clause 4.1.11>>, Note 1 to entry has been added from <<ISO19156-2011,clause 4.6>>, and modified

[[feature_type]]
=== feature type

_class_ (<<class>>) of _features_ (<<feature>>) having common characteristics

[.source]
<<ISO19156-2011,clause 4.7>>

[[geodetic_coordinate_reference_system]]
=== geodetic coordinate reference system
alt:[geodetic CRS]

three-dimensional _coordinate reference system_ (<<coordinate_reference_system>>) based on
a geodetic reference frame and having either a three-dimensional Cartesian or a spherical coordinate system

NOTE: In this document a CRS  based on
a geodetic reference frame and having an ellipsoidal coordinate system is geographic.

[.source]
<<ISO19111-2019,clause 3.1.31>>

[[geographic_coordinate_reference_system]]
=== geographic coordinate reference system
alt:[geographic CRS]

coordinate reference system (<<coordinate_reference_system>>) that has a geodetic reference frame and an ellipsoidal coordinate system

[.source]
<<ISO19111-2019,clause 3.1.35>>

[[geographic_identifier]]
=== geographic identifier

_spatial reference_ (<<spatial_reference>>) in the form of a label or code that identifies a _location_ (<<location>>)

[example]
“Spain” is an example of a label (country name); “SW1P 3AD” is an example of a code (postcode).

[.source]
<<ISO19112-2019,clause 3.1.2>>

[[geometric_primitive]]
=== geometric primitive

geometric object representing a single, connected, homogeneous (isotropic) element of space

NOTE:  Geometric primitives are non-decomposed objects that present information about geometric configuration.
They include points, curves, surfaces, and solids.
Many geometric objects behave like primitives (supporting the same interfaces defined for geometric primitives)
but are actually composites composed of some number of other primitives.
General collections may be aggregates and incapable of acting like
a primitive (such as the lines of a complex network,
which is not connected and thus incapable of being traceable as a single line).
By this definition, a geometric primitive is topological open,
since the _boundary_ (<<boundary>>) points are not isotropic to the interior points.
Geometry is assumed to be closed. For points, the boundary is empty.

[.source]
<<ISO19107-2019,clause 3.50>>

[[globe]]
=== globe

<DGGS> region of space-time enclosing a celestial body

NOTE: In this document globe is used in its most general form to
refer to any celestial body or region of space-time enclosing a celestial body that may be referenced by a
_DGGS_ (<<dggs>>).
When a specific body, such as the Earth is referred to, an explicit term is used.

[[grid]]
=== grid

network composed of two or more sets of curves in which the members of each set intersect the members of the other sets in an algorithmic way

NOTE: The curves partition a space into grid cells.

[.source]
<<ISO19123-2005,clause 4.1.23>>

[[hierarchy]]
=== hierarchy

<DGGS> organization and ranking of successive levels of _cell refinement_ (<<cell_refinement>>) of _discrete global grids_ (<<discrete_global_grid>>)

[[initial_discrete_global_grid]]
=== initial discrete global grid

<DGGS> discrete global grid tessellation created by circumscribing a defined path along the chosen surface model of the Earth
between the vertices of the scaled base unit polyhedron

[[interoperability]]
=== interoperability

capability to communicate, execute programmes, or transfer data among various functional units in a manner that requires the user to have little or no knowledge of the unique characteristics of those units

NOTE: in this document interoperability specifically refers to functions that initiate and process transfers of data from a DGGS (<<dggs>>).

[.source]
<<ISO2382-2015,clause 2121317>>, The original domain and Notes to Entry have been deleted. A Note 1 to entry has been added.

[[instant]]
=== instant

<DGGS> temporal geometry primitive representing a point in time

NOTE: On _temporal coordinate systems_ (<<temporal_coordinate_system>>)
as specified in <<ISO19107>>,
the temporal _geometric primitives_ (<<geometric_primitive>>) instant and
_interval_ (<<interval>>) are the equivalent of points and lines as specified in <<ISO19107>>.

[[interval]]
=== interval

<DGGS> temporal geometry primitive representing a line in time

NOTE: On _temporal coordinate systems_ (<<temporal_coordinate_system>>)
as specified in (<<ISO19107>>),
the temporal _geometric primitives_ (<<geometric_primitive>>) _instant_ (<<instant>>) and
interval are the equivalent of points and lines as specified in <<ISO19107>>.

[[location]]
=== location

particular place or position

NOTE: A location identifies a geographic place.

NOTE: In the context of _DGGS_ (<<dggs>>),
locations have dimension greater than one, and so are not points.

[example]
“Madrid”, “SW1P 3AD”.

[.source]
<<ISO19112-2019,clause 3.1.3>>, Note two has been added and an additional example provided

[[observation]]
=== observation

act of measuring or otherwise determining the _value_ (<<value>>) of a property

[.source]
<<ISO19156-2011,clause 4.11>>

[[parent_cell]]
=== parent cell
alt:[parent]

<DGGS> _cell_ (<<cell>>) in a higher refinement level of discrete global grid with immediate descendants

NOTE: parent cells either overlap or contain their _child cells_ (<<child_cell>>).

[[period]]
=== period

<DGGS> particular era or span of time

NOTE: Periods are _intervals_ (<<interval>>) named with a _period identifier_ (<<period_identifier>>)

[[period_identifier]]
=== period identifier

<DGGS> temporal reference in the form of a label or code that identifies a _period_ (<<period>>)

NOTE: Period identifiers are the temporal equivalent of _geographic identifiers_ (<<geographic_identifier>>) as specified in <<ISO19112>>

[[quantization]]
=== quantization

<DGGS> function assigning data from external sources to cell values

[[refinement_level]]
=== refinement level

<DGGS> numerical order of a _discrete global grid_ (<<discrete_global_grid>>) in the tessellation sequence

NOTE: The tessellation with the smallest number of cells has a refinement level = 0.

[[refinement_ratio]]
=== refinement ratio

<DGGS> ratio of the number of _child cells_ (<<child_cell>>) to _parent cells_ (<<parent_cell>>)

NOTE: A positive integer ratio n refinement of _DGGS_ (<<dggs>>) parent cells yield n times as many child cells as parent cells.

NOTE: For a two-dimensional DGGS (as defined for EAERS in this document) this is the surface area ratio.

NOTE: In DGGS literature <<ref2>> the term aperture has been used instead of refinement ratio.
Refinement ratio is preferred because it is clearer in meaning to audiences outside the early DGGS community.

[[sibling_cell]]
=== sibling cell
alt:[sibling]

<DGGS> _cell_ (<<cell>>) in a discrete global grid with the same _parent cell_ (<<parent_cell>>)

NOTE: all the _child cells_ (<<child_cell>>) of a parent cell are each-others' sibling cells.

[[simple]]
=== simple

<topology, geometry> homogeneous (all points have isomorphic neighbourhoods) and with a simple _boundary_ (<<boundary>>)

NOTE: The interior is everywhere locally isomorphic to an open disc in a Euclidean coordinate space of the appropriate dimension `D^n^ = {P|‖P‖ &lt; 1.0}`.
The boundary is a dimension one smaller.
This essentially means that the object does not intersect nor touch itself.
Generally used for a curve that does not cross not touch itself with the possible exception of boundary points.
Simple closed curves are isomorphic to a circle.

[.source]
<<ISO19107-2019,clause 3.84>>

[[spatial_reference]]
=== spatial reference

description of position in the real world

NOTE: This may take the form of a label, code or coordinate tuple.

[.source]
<<ISO19111-2019,clause 3.1.56>>

[[spatio-temporal_reference]]
=== spatio-temporal reference

system for identifying position in the real world that may include time

NOTE: This may take the form of a label, code or coordinate tuple.

[[spatio-temporal_coordinate_reference_system]]
=== spatio-temporal coordinate reference system
alt:[spatio-temporal CRS]

_compound coordinate reference system_ (<<compound_coordinate_reference_system>>) in which one constituent _coordinate reference system_ (<<coordinate_reference_system>>) is a spatial coordinate reference system and one is a _temporal coordinate reference system_ (<<temporal_coordinate_reference_system>>)

[.source]
<<ISO19111-2019,clause 3.1.59>>

[[static_coordinate_reference_system]]
=== static coordinate reference system
alt:[static CRS]

_coordinate reference system_ (<<coordinate_reference_system>>) that has a _static reference frame_ (<<static_reference_frame>>)

NOTE: Coordinates of points on or near the crust of the Earth that are referenced to a dynamic coordinate reference system do not change with time.

NOTE: Metadata for a dataset referenced to a static coordinate reference system does not require coordinate epoch information.

[.source]
<<ISO19111-2019,clause 3.1.61>>

[[static_reference_frame]]
=== static reference frame
alt:[static datum]

_reference frame_ (<<datum>>) in which the defining parameters exclude time evolution

[.source]
<<ISO19111-2019,clause 3.1.62>>

[[temporal_coordinate_system]]
=== temporal coordinate system

<geodesy> one-dimensional coordinate system where the axis is time

[.source]
<<ISO19111-2019,clause 3.1.64>>

[[temporal_coordinate_reference_system]]
=== temporal coordinate reference system
alt:[temporal CRS]

coordinate reference system (<<coordinate_reference_system>>) based on a temporal datum

[.source]
<<ISO19111-2019,clause 3.1.63>>

[[tessellation]]
=== tessellation

partitioning of a space into a set of conterminous subspaces having the same dimension as the space being partitioned

[example]
Graphic examples of tessellations may be found in Figures 11, 13, 20, and 22 of <<ISO19123>>.

NOTE: A tessellation composed of congruent regular polygons or polyhedra is a regular tessellation.
One composed of regular, but non-congruent polygons or polyhedra is a semi-regular tessellation.
Otherwise the tessellation is irregular.
Tessellations on curved surfaces cannot be congruent, so all tessellations in DGGS (<<dggs>>) are either semi-regular or irregular.

[.source]
<<ISO19123-2005,clause 4.1.39>>, Note 1 to entry has been modified and new notes to entry have been added.

[[value]]
=== value

element of a type domain

NOTE: A value considers a possible state of an object within a _class_ (<<class>>) or type (domain).

NOTE: A data value is an instance of a datatype, a value without identity.

NOTE: A value can use one of a variety of scales including nominal, ordinal, ratio and interval, spatial and temporal.
Primitive datatypes can be combined to form aggregate datatypes with aggregate values, including vectors, tensors and images.

[.source]
<<ISO19156,clause 4.18>>

[[zonal_query]]
=== zonal query

<DGGS> geometry or topology function using a cell's _zonal identifiers_ (<<zonal_identifier>>) to specify geometry

NOTE: <<ISO19107>> specifies a suite of geometry and topology functions in the Query2D and Query3D classes,
where geometry elements used in each function's parameters are described by sets of coordinates.
In DGGS (<<dggs>>) all geometry can be referenced as sets of _cells_ (<<cell>>) represented solely by a list (or set) of their zonal identifiers.
This document specifies ZoneQuery to implement the operations in both Query2D and Query3D using
zonal identifiers to reference each operation's source and target geometry.

[[zonal_identifier]]
=== zonal identifier

<DGGS> _spatio-temporal reference_ (<<spatio-temporal_reference>>) in the form of a label or code that identifies a _zone_ (<<zone>>)

NOTE: A zonal identifier may be a _geographic identifier_ (<<geographic_identifier>>), _period identifier_ (<<period_identifier>>), or a compound of the two.

NOTE: A zone's ZonalIdentifier provides the coordinates of a representative position for the zone,
and spatio-temporal feature geometry is represented by sets of ZonalIdentifiers.

[[zone]]
=== zone

<DGGS> particular region of space-time

NOTE: The primitives of zone are spatial _location_ (<<location>>) and temporal _period_ (<<period>>).

NOTE: A zone may be either a single zonal primitive or a compound zone comprising one spatial location and one temporal period. Zones can be regions of space-time associated with any celestial body.

NOTE: Zones are the primary container for storing and retrieving data within a DGGS implementation.
DGGSs reference zones by their _zonal identifier_ (<<zonal_identifier>>), for instance in databases or through tile nomenclature.

NOTE: Each zone's geometry is represented by a cell (<<cell>>).
