[[AnyFeature-section]]
==== AnyFeature (from <<iso19109,ISO 19109:2015>>)

.Metadata of AnyFeature (class)
[cols="1a,4a"]
|===
h|Definition: | AnyFeature is an abstract class that is the generalization of all feature types. AnyFeature is an instance of the «metaclass» FeatureType [cf. ISO 19109].
h|Subclass of: | none
h|Stereotype: | «FeatureType»
|===

.Associations of AnyFeature (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition
|
|{{FeatureType}} [1..1]
|
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[CV_DiscreteGridPointCoverage-section]]
==== CV_DiscreteGridPointCoverage (from <<iso19123,ISO 19123:2005>>)

.Metadata of CV_DiscreteGridPointCoverage (class)
[cols="1a,4a"]
|===
h|Definition: | A coverage that returns the same feature attribute values for every direct position within any single spatial object, temporal object or spatiotemporal object in its domain.
h|Subclass of: | {{CV_DiscreteCoverage}}
h|Stereotype: | «type»
|===

.Associations of CV_DiscreteGridPointCoverage (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition
| element
|{{CV_GridPointValuePair}} [1..*]
|
| valueAssignment
|{{CV_GridValuesMatrix}} [1..1]
|
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[DirectPosition-section]]
==== DirectPosition (from <<iso19107>>)

.Metadata of DirectPosition (class)
[cols="1a,4a"]
|===
h|Definition: | DirectPosition object data types (Figure 14) hold the coordinates for a position within some coordinate reference system. The coordinate reference system is described in ISO 19111. Since DirectPositions, as data types, will often be included in larger objects (such as GM_Objects) that have references to ISO19111::SC_CRS, the DirectPosition::cordinateReferenceSystem may be left NULL if this particular DirectPosition is included in a larger object with such a reference to a SC_CRS. In this case, the DirectPosition::cordinateReferenceSystem is implicitly assumed to take on the value of the containing object's SC_CRS.
h|Subclass of: | None
h|Stereotype: | None
|===

.Associations of DirectPosition (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition
| CRS |{{CRS}} [0..1]|
| CRS |{{SC_CRS}} [0..1]|
|===

.Attributes of DirectPosition (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition
| coordinate   |Sequence {{number}} [1..1]|
| dimension   |{{Integer}} [1..1] |
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_Object-section]]
==== GM_Object (from <<iso19107>>)

.Metadata of GM_Object (class)
[cols="1a,4a"]
|===
h|Definition: | GM_Object is the root class of the geometric object taxonomy and supports interfaces common to all geographically referenced geometric objects. GM_Object instances are sets of direct positions in a particular coordinate reference system. A GM_Object can be regarded as an infinite set of points that satisfies the set operation interfaces for a set of direct positions, TransfiniteSet<DirectPosition>. Since an infinite collection class cannot be implemented directly, a Boolean test for inclusion shall be provided by the GM_Object interface. This international standard concentrates on vector geometry classes, but future work may use GM_Object as a root class without modification.

NOTE: As a type, GM_Object does not have a well-defined default state or value representation as a data type. Instantiated subclasses of GM_Object will.

h|Subclass of: | none
h|Stereotype: | «type»
|Constraint: | `dimension() >  boundary().dimension (Invariant):`
|Constraint: | `boundary().notEmpty() implies boundary().dimension() = dimension() -1 (Invariant):`
|Constraint: | `boundary().isEmpty() = isCycle() (Invariant):`
|===

.Associations of GM_Object (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition

|
|{{Geometry}} [1..1]
|

|
|TransfiniteSet{{DirectPosition}} [1..1]
|

|
|{{CV_DomainObject}} [1..1]
|

| CRS
|{{CRS}} [0..1]
|

| CRS
|{{SC_CRS}} [0..1]
|

|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_MultiCurve-section]]
==== GM_MultiCurve (from <<iso19107>>)

.Metadata of GM_MultiCurve (class)
[cols="1a,4a"]
|===
h|Definition: | An aggregate class containing only instances of GM_OrientableCurve. The association role “element” shall be the set of GM_OrientableCurves contained in this GM_MultiCurve.
h|Subclass of: | {{GM_MultiPrimitive}}
h|Stereotype: | «type»
|===

.Attributes of GM_MultiCurve (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition

| length  |{{Length}} [1..1] |
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_MultiPoint-section]]
==== GM_MultiPoint (from <<iso19107>>)

.Metadata of GM_MultiPoint (class)
[cols="1a,4a"]
|===
h|Definition: | GM_MultiPoint is an aggregate class containing only points. The association role “element” shall be the set of GM_Points contained in this GM_MultiPoint.
h|Subclass of: | {{GM_MultiPrimitive}}
h|Stereotype: | «type»
|===

.Attributes of GM_MultiPoint (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition

| position   |Set  {{DirectPosition}} [1..1] |
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_MultiSurface-section]]
==== GM_MultiSurface (from <<iso19107>>)

.Metadata of GM_MultiSurface (class)
[cols="1a,4a"]
|===
h|Definition: | An aggregate class containing only instances of GM_OrientableSurface. The association role “element” shall be the set of GM_OrientableSurfaces contained in this GM_MultiSurface.
h|Subclass of: | {{GM_MultiPrimitive}}
h|Stereotype: | «type»
|===

.Attributes of GM_MultiSurface (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition

| area   |{{Area}} [1..1] |

| perimeter   |{{Length}} [1..1] |
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_Point-section]]
==== GM_Point (from <<iso19107>>)

.Metadata of GM_Point (class)
[cols="1a,4a"]
|===
h|Definition: | GM_Point is the basic data type for a geometric object consisting of one and only one point.
h|Subclass of: | {{GM_Primitive}}
h|Stereotype: | «type»
|===

.Associations of GM_Point (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition
|
|{{Point}} [1..1]
|
| composite
|{{GM_CompositePoint}} [0..*]
|
|===

.Attributes of GM_Point (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition

| position   |{{DirectPosition}} [1..1]  |The attribute "position" shall be the DirectPosition of this GM_Point.

NOTE: In most cases, the state of a GM_Point is fully determined by its position attribute. The only exception to this is if the GM_Point has been subclassed to provide additional non-geometric information such as symbology.
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_Solid-section]]
==== GM_Solid (from <<iso19107>>)

.Metadata of GM_Solid (class)
[cols="1a,4a"]
|===
h|Definition: | GM_Solid, a subclass of GM_Primitive, is the basis for 3-dimensional geometry. The extent of a solid is defined by the boundary surfaces.
h|Subclass of: | {{GM_Primitive}}
h|Stereotype: | «type»
|===

.Associations of GM_Solid (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition
| composite
|{{GM_CompositeSolid}} [0..*]
|
|
|{{Solid}} [1..1]
|
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_Surface-section]]
==== GM_Surface (from <<iso19107>>)

.Metadata of GM_Surface (class)
[cols="1a,4a"]
|===
h|Definition: | GM_Surface is a subclass of GM_Primitive and is the basis for 2-dimensional geometry. Unorientable surfaces such as the Möbius band are not allowed. The orientation of a surface chooses an "up" direction through the choice of the upward normal, which, if the surface is not a cycle, is the side of the surface from which the exterior boundary appears counterclockwise. Reversal of the surface orientation reverses the curve orientation of each boundary component, and interchanges the conceptual "up" and "down" direction of the surface. If the surface is the boundary of a solid, the "up" direction is usually outward. For closed surfaces, which have no boundary, the up direction is that of the surface patches, which must be consistent with one another. Its included GM_SurfacePatches describe the interior structure of a GM_Surface.

NOTE: Other than the restriction on orientability, no other "validity" condition is required for GM_Surface.

h|Subclass of: | {{GM_OrientableSurface}}
h|Stereotype: | «type»
|===

.Associations of GM_Surface (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition
|
|{{GM_GenericSurface}} [1..1]
|
|
|{{Building}} [0..*]
|
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_Tin-section]]
==== GM_Tin (from <<iso19107>>)

.Metadata of GM_Tin (class)
[cols="1a,4a"]
|===
h|Definition: | A GM_Tin is a GM_TriangulatedSurface that uses the Delaunay algorithm or a similar algorithm complemented with consideration for breaklines, stoplines and maximum length of triangle sides (Figure 22). These networks satisfy the Delaunay criterion away from the modifications: For each triangle in the network, the circle passing through its vertexes does not contain, in its interior, the vertex of any other triangle.
h|Subclass of: | {{GM_TriangulatedSurface}}
h|Stereotype: | «type»
|===

.Attributes of GM_Tin (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition

| breakLines   |Set {{GM_LineString}} [1..1] |

| controlPoint   |{{GM_Position}}  [3..*] |

| maxLength   |{{Distance}} [1..1] |

| stopLines   |Set {{GM_LineString}} [1..1] |
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[GM_TriangulatedSurface-section]]
==== GM_TriangulatedSurface (from <<iso19107>>)

.Metadata of GM_TriangulatedSurface (class)
[cols="1a,4a"]
|===
h|Definition: | A GM_TriangulatedSurface is a GM_PolyhedralSurface that is composed only of triangles (GM_Triangle). There is no restriction on how the triangulation is derived.
h|Subclass of: | {{GM_PolyhedralSurface}}
h|Stereotype: | «type»
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[SC_CRS-section]]
==== SC_CRS (from <<iso19111,ISO 19111:2019>>)

.Metadata of SC_CRS (class)
[cols="1a,4a"]
|===
h|Definition: | Coordinate reference system which is usually single but may be compound.
h|Subclass of: | {{IO_IdentifiedObjectBase}}, {{RS_ReferenceSystem}}
h|Stereotype: | «type»
|===

.Associations of SC_CRS (class)
[cols="15a,20a,60a",options="header"]
|===
| Role name | Target class and multiplicity | Definition
| coordOperationTo
|{{CC_CoordinateOperation}} [0..*]
|Not-navigable association from a Coordinate Operation that uses ths CRS as its targetCRS.
| grid
|{{CV_ReferenceableGrid}} [0..*]
|
|===

.Attributes of SC_CRS (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition

| scope   |{{CharacterString}}  [1..*] |Description of usage, or limitations of usage, for which this CRS is valid. If unknown, enter "not known".
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


[[TM_Position-section]]
==== TM_Position (from <<iso19108,ISO 19108:2006>>)

.Metadata of TM_Position (class)
[cols="1a,4a"]
|===
h|Definition: | TM_Position is a union class that consists of one of the data types listed as its attributes. Date, Time, and DateTime are basic data types defined in ISO/TS 19103.
h|Subclass of: | None
h|Stereotype: | «Union»
|===

.Attributes of TM_Position (class)
[cols="15a,20a,60a",options="header"]
|===
| Attribute | Value type and multiplicity | Definition

| anyOther   |{{TM_TemporalPosition}} [1..1] |

| date8601   |{{Date}} [1..1] |

| time8601   |{{Time}} [1..1] |

| dateTime8601   |{{DateTime}} [1..1] |
|===

NOTE: Unless otherwise specified, all attribute and role names have the stereotype «Property»


