The following requirement defines the rules governing implementation of the CityGML Transportation Module as an Implementation Specification.

[[req_transportation_classes]]
[requirement,type="general",label="/req/transportation/classes"]
====
For each UML class defined or referenced in the Transportation Package:

[.component,class=part]
--
The Implementation Specification SHALL contain an element which represents the same concept as that defined for the UML class.
--

[.component,class=part]
--
The Implementation Specification SHALL represent associations with the same source, target, direction, roles, and multiplicities as those of the UML class.
--

[.component,class=part]
--
The implementation Specification SHALL represent the attributes of the UML class including the name, definition, type, and multiplicity.
--

[.component,class=part]
--
The implementation Specification SHALL represent the attributes of all superclasses of the UML class including the name, definition, type, and multiplicity.
--

[.component,class=part]
--
The implementation Specification SHALL represent the associations of all superclasses of the UML class including the source, target, direction, roles, and multiplicity.
--

[.component,class=part]
--
The Implementation Specification SHALL specify how an implementation observes all constraints the Conceptual Model imposes on the UML class.
--
====
