The CityGML Core defines technology-agnostic concepts. These concepts are then realized in technology-specific Implementation Specifications. The following requirements govern the creation of any CityGML compliant Implementation Specification (IS).

[[req_core_classes]]
[requirement,type="general",label="/req/core/classes"]
====
For each UML class defined or referenced in the Core Package:

[.component,class=part]
--
The Implementation Specification SHALL contain an element which represents the same concept as that defined for the UML class.
--

[.component,class=part]
--
The Implementation Specification SHALL represent associations with the same source, target, direction, roles, and multiplicities as those of the UML class.
--

[.component,class=part]
--
The implementation Specification SHALL represent the attributes of the UML class including the name, definition, type, and multiplicity.
--

[.component,class=part]
--
The implementation Specification SHALL represent the attributes of all superclasses of the UML class including the name, definition, type, and multiplicity.
--

[.component,class=part]
--
The implementation Specification SHALL represent the associations of all superclasses of the UML class including the source, target, direction, roles, and multiplicity.
--

[.component,class=part]
--
The Implementation Specification SHALL specify how an implementation observes all constraints the Conceptual Model imposes on the UML class.
--
====


While the CityGML Conceptual Model builds on ISO Standards, there are some restrictions on the use of those standards.

[[req_Core_iso-restrictions]]
[requirement,type="general",label="/req/Core/isorestrictions"]
====
ISO classes used in the CityGML Conceptual Model are subject to the following restrictions:

[.component,class=part]
--
Classes derived from the GM_Solid class (ISO 19107) SHALL only include exterior boundaries. (The `interior` association on the GM_SolidBoundary shall not be defined)
--
====

An implementing technology may not be able to support all of the concepts defined in the CityGML Conceptual Model. Alternately, some concepts from the Conceptual Model may be inappropriate for the application domain for which the Implementation Specification was developed. In those cases, elements of the Conceptual Model may be mapped to null elements in the Implementation Specification.

[[per_Core_classes]]
[.permission,label="/per/Core/classes"]
====
For each UML class defined or referenced in CityGML Conceptual Model:

[.component,class=part]
--
An Implementation Specification MAY represent that class as a null class with no attributes, associations, or definition.
--

[.component,class=part]
--
An Implementation Specification MAY represent an association of the UML class with a null association.
--

[.component,class=part]
--
An Implementation Specification MAY represent an attribute of the UML class with a null attribute.
--

[.component,class=part]
--
Whenever a null element is used to represent a concept from the Conceptual Model, the Implementation Specification SHOULD document that mapping and provide an explanation for why that concept was not implemented.
--
====

