packages:
  - "Appearance"
  - "Bridge"
  - "Building"
  - "CityFurniture"
  - "CityObjectGroup"
  - "Construction"
  - "Core"
  - "Dynamizer"
  - "Generics"
  - "LandUse"
  - "Pointcloud"
  - "Relief"
  - "Transportation"
  - "Tunnel"
  - "Vegetation"
  - "Versioning"
  - "WaterBody"
section_depth: 3
render_style: data_dictionary