== Conformance
This standard defines the conformance classes listed in tables <<tab-conf-cc>>&ndash;<<tab-conf-ea-ers>>

[[tab-conf-cc]]
include::../abstract_tests/TEST_cc-i.adoc[]

[[tab-conf-core]]
include::../abstract_tests/TEST_core-i.adoc[]

[[tab-conf-ea-ers]]
include::../abstract_tests/TEST_ea-ers-i.adoc[]

//  http://www.opengis.net/spec/dggs/1.0/req/core with a single pertaining conformance class, core, with URI http://www.opengis.net/spec/dggs/1.0/conf/core.

Conformance with this standard shall be checked using the relevant tests specified in <<AnnexA>> (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

////
In order to conform to this OGC® interface standard, a software implementation shall choose to implement:

* Any one of the conformance levels specified in <<AnnexA>> (normative).
* Any one of the Distributed Computing Platform profiles specified in Annexes TBD through TBD (normative).
////

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.
