[appendix]
= Glossary

[heading='terms and definitions']
== General

=== conformance test class

The set of conformance test modules that must be applied to receive a single certificate of
conformance

[.source]
<<ogc08-131,clause=4.4>>


=== feature

An abstraction of real world phenomena

[.source]
<<iso19101-1,clause=4.1.11>>

=== feature attribute

A characteristic of a feature

[.source]
<<iso19101-1,clause=4.1.12>>


[[FeatureType-section]]
=== feature type

A class of features having common characteristics

[.source]
<<iso19156,clause=4.7>>


=== measurement

A set of operations having the object of determining the value of a quantity

[.source]
<<iso19101-2:2018,clause=3.21>>
//<<VIM,clause=2.1>>


=== model

An abstraction of some aspects of reality

[.source]
<<iso19109,clause=4.15>>


=== observation

The act of measuring or otherwise determining the value of a property

[.source]
<<iso19156,clause=4.11>>

=== observation procedure

A method, algorithm or instrument, or system of these, which may be used in making an
observation

[.source]
<<iso19156,clause=4.12>>

=== observation result

An estimate of the value of a property determined through a known observation procedure

[.source]
<<iso19156,clause=4.14>>

=== property

A facet or attribute of an object referenced by a name.

[.source]
<<iso19143,clause=4.21>>

=== requirements class

The aggregate of all requirement modules that must all be satisfied to satisfy a conformance
test class

[.source]
<<ogc08-131,clause=4.19>>


=== schema

The formal description of a model

[.source]
<<iso19101-1,clause=4.1.34>>


=== sensor

A type of observation procedure that provides the estimated value of an observed
property at its output

[.source]
<<ogc08-094r1,clause=4.5>>

[[standardization-target-definition]]
=== Standardization Target

An entity to which some requirements of a standard apply

[.source]
<<ogc08-131,clause=4.23>>

=== timeseries

A sequence of data values which are ordered in time

[.source]
<<ogc15-043r3>>


=== universe of discourse

View of the real or hypothetical world that includes everything of interest

[.source]
<<iso19101-1,clause=4.1.38>>


=== version

Particular variation of a spatial object

[.source]
<<inspire_glossary>>


[heading='terms and definitions']
== ISO Concepts

The following concepts from the ISO TC211 Harmonized UML model are referenced by the CityGML Conceptual UML model but do not play a major role in its' definition. They are provided here to support a more complete understanding of the model.

[[Area-section]]
=== Area

The measure of the physical extent of any topologically 2-D geometric object. Usually measured in "square" units of length.

[.source]
<<iso19103>>


[[Boolean-section]]
=== Boolean

Boolean is the mathematical datatype associated with two-valued logic

[.source]
<<iso19103>>

[[CC_CoordinateOperation-section]]
=== CC_CoordinateOperation

A mathematical operation on coordinates that transforms or converts coordinates to another coordinate reference system.

[.source]
<<iso19111>>


[[Character-section]]
=== Character

A symbol from a standard character-set.

[.source]
<<iso19103>>


[[CharacterString-section]]
=== CharacterString

CharacterString is a family of datatypes which represent strings of symbols from standard character-sets.

[.source]
<<iso19103>>


[[CRS-section]]
=== CRS

Coordinate reference system which is usually single but may be compound.

[.source]
<<iso19111>>


[[CV_DiscreteCoverage-section]]
=== CV_DiscreteCoverage

A subclass of CV_Coverage that returns a single record of values for any direct position within a single geometric object in its spatiotemporal domain.

[.source]
<<iso19123>>


[[CV_DomainObject-section]]
=== CV_DomainObject

An element of the domain of the CV_Coverage. It is an aggregation of objects that may include any combination of GM_Objects (ISO 19107:2003), TM_GeometricPrimitives (ISO 10108), or spatial or temporal objects defined in other standards, such as the CV_GridPoint defined in this International Standard.

[.source]
<<iso19123>>


[[CV_GridPointValuePair-section]]
=== CV_GridPointValuePair

A subtype of CV_GeometryValuePair that has a GM_GridPoint as the value of its geometry attribute.

[.source]
<<iso19123>>


[[CV_GridValuesMatrix-section]]
=== CV_GridValuesMatrix

The geometry represented by the various offset vectors is in the image plane of the grid.

[.source]
<<iso19123>>


[[CV_ReferenceableGrid-section]]
=== CV_ReferenceableGrid

A subclass of CV_Coverage that relates the grid coordinates to an external coordinate reference system.

[.source]
<<iso19123>>


[[Date-section]]
=== Date

Date gives values for year, month and day. Representation of Date is specified in ISO 8601. Principles for date and time are further discussed in ISO 19108.

[.source]
<<iso19103>>


[[DateTime-section]]
=== DateTime

A DateTime is a combination of a date and a time types. Representation of DateTime is specified in ISO 8601. Principles for date and time are further discussed in ISO 19108.

[.source]
<<iso19103>>


[[Distance-section]]
=== Distance

Used as a type for returning distances and possibly lengths.

[.source]
<<iso19103>>


[[EngineeringCRS-section]]
=== Engineering CRS
A contextually local coordinate reference system which can be divided into two broad categories:

. earth-fixed systems applied to engineering activities on or near the surface of the earth;

. CRSs on moving platforms such as road vehicles, vessels, aircraft or spacecraft.

[.source]
<<iso19111>>


[[GenericName-section]]
=== Generic Name

Generic Name is the abstract class for all names in a NameSpace. Each instance of a GenericName is either a LocalName or a ScopedName.

[.source]
<<iso19103>>


[[Geometry-section]]
=== Geometry

Geometry is the root class of the geometric object taxonomy and supports interfaces common to all geographically referenced geometric objects.

[.source]
<<iso19107>>


[[GM_CompositePoint-section]]
=== GM_CompositePoint

A GM_Complex containing one and only one GM_Point.

[.source]
<<iso19107>>


[[GM_CompositeSolid-section]]
=== GM_CompositeSolid

A set of geometric solids adjoining one another along common boundary geometric surfaces

[.source]
<<iso19107>>


[[GM_GenericSurface-section]]
=== GM_GenericSurface

GM_Surface and GM_SurfacePatch both represent sections of surface geometry, and therefore share a number of operation signatures. These are defined in the interface class GM_GenericSurface.

[.source]
<<iso19107>>


[[GM_LineString-section]]
=== GM_LineString

Consists of sequence of line segments, each having a parameterization like the one for GM_LineSegment

[.source]
<<iso19107>>


[[GM_MultiPrimitive-section]]
=== GM_MultiPrimitive

The root class for all primitive aggregates. The association role “element” shall be the set of GM_Primitives contained in this GM_MultiPrimitive. The attribute declaration here specializes the one at GM_Aggregate to include only GM_Primitives in this type of aggregate.

[.source]
<<iso19107>>


[[GM_OrientableSurface-section]]
=== GM_OrientableSurface

A surface and an orientation inherited from GM_OrientablePrimitive. If the orientation is "+", then the GM_OrientableSurface is a GM_Surface. If the orientation is "-", then the GM_OrientableSurface is a reference to a GM_Surface with an upNormal that reverses the direction for this GM_OrientableSurface, the sense of "the top of the surface".

[.source]
<<iso19107>>


[[GM_PolyhedralSurface-section]]
=== GM_PolyhedralSurface

A GM_Surface composed of polygon surfaces (GM_Polygon) connected along their common boundary curves.

[.source]
<<iso19107>>


[[GM_Position-section]]
=== GM_Position

A union type consisting of either a DirectPosition or of a reference to a GM_Point from which a DirectPosition shall be obtained.

[.source]
<<iso19107>>


[[GM_Primitive-section]]
=== GM_Primitive

The abstract root class of the geometric primitives. Its main purpose is to define the basic "boundary" operation that ties the primitives in each dimension together.

[.source]
<<iso19107>>


[[Integer-section]]
=== Integer

An exact integer value, with no fractional part.

[.source]
<<iso19103>>


[[IoT_definition]]
=== Internet of Things

The network of physical objects--“things”--that are embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the Internet. +

[.source]


[[IO_IdentifiedObjectBase-section]]
=== IO_IdentifiedObjectBase

Supplementary identification and remarks information for a CRS or CRS-related object.

[.source]
<<iso19111>>


[[Length-section]]
=== Length

The measure of distance as an integral, i.e. the limit of an infinite sum of distances between points on a curve.

[.source]
<<iso19103>>


[[Measure-section]]
=== Measure

The result from performing the act or process of ascertaining the extent, dimensions, or quantity of some entity.

[.source]
<<iso19103>>


[[number-section]]
=== Number

The base type for all number data, giving the basic algebraic operations.

[.source]
<<iso19103>>


[[Point-section]]
=== Point

GM_Point is the basic data type for a geometric object consisting of one and only one point.

[.source]
<<iso19107>>


[[Real-section]]
=== Real

The common binary Real finite implementation using base 2.

[.source]
<<iso19103>>


[[RS_ReferenceSystem-section]]
=== RS_ReferenceSystem

Description of a spatial and temporal reference system used by a dataset.

[.source]
<<iso19111>>


[[ScopedName-section]]
=== Scoped Name

ScopedName is a composite of a LocalName for locating another NameSpace and a GenericName valid in that NameSpace. ScopedName contains a LocalName as head and a GenericName, which might be a LocalName or a ScopedName, as tail.

[.source]
<<iso19103>>


[[Solid-section]]
=== Solid

GM_Solid, a subclass of GM_Primitive, is the basis for 3-dimensional geometry. The extent of a solid is defined by the boundary surfaces.

[.source]
<<iso19107>>


[[Time-section]]
=== Time

Time is the designation of an instant on a selected time scale, astronomical or atomic. It is used in the sense of time of day.

[.source]
<<iso19103>>


[[TM_Duration-section]]
=== TM_Duration

A data type to be used for describing length or distance in the temporal dimension.

[.source]
<<iso19108>>


[[TM_TemporalPosition-section]]
=== TM_TemporalPosition

The position of a TM_Instant relative to a TM_ReferenceSystem.

[.source]
<<iso19108>>


[[UnitOfMeasure-section]]
=== Unit of Measure

Any of the systems devised to measure some physical quantity such distance or area or a system devised to measure such things as the passage of time.

[.source]
<<iso19103>>


[[URI-section]]
=== URI

Uniform Resource Identifier (URI), is a compact string of characters used to identify or name a resource

[.source]
<<iso19103>>


[[Volume-section]]
=== Volume

Volume is the measure of the physical space of any 3-D geometric object.

[.source]
<<iso19103>>


== Abbreviated Terms

2D:: Two Dimensional
3D:: Three Dimensional
AEC:: Architecture, Engineering, Construction
ALKIS:: German National Standard for Cadastral Information
ATKIS:: German National Standard for Topographic and Cartographic Information
BIM:: Building Information Modeling
B-Rep:: Boundary Representation
bSI:: buildingSMART International
CAD:: Computer Aided Design
COLLADA:: Collaborative Design Activity
CSG:: Constructive Solid Geometry
DTM:: Digital Terrain Model
DXF:: Drawing Exchange Format
EuroSDR:: European Spatial Data Research Organisation
ESRI:: Environmental Systems Research Institute
FM:: Facility Management
GDF:: Geographic Data Files
GDI-DE:: Spatial Data Infrastructure Germany (Geodateninfrastruktur Deutschland)
GDI:: NRW Geodata Infrastructure North-Rhine Westphalia
GML:: Geography Markup Language
IAI:: International Alliance for Interoperability (now buildingSMART International (bSI))
IETF:: Internet Engineering Task Force
IFC:: Industry Foundation Classes
IoT:: Internet of Things
ISO:: International Organization for Standardisation
ISO/TC211:: ISO Technical Committee 211
LOD:: Levels of Detail
MQTT:: TODO
NBIMS:: National Building Information Model Standard
OASIS:: Organisation for the Advancement of Structured Information Standards
OGC:: Open Geospatial Consortium
OSCRE:: Open Standards Consortium for Real Estate
SIG:: Special Interest Group 3D of the GDI-DE
TIC:: Terrain Intersection Curve
TIN:: Triangulated Irregular Network
UML:: Unified Modeling Language
URI:: Uniform Resource Identifier
VRML:: Virtual Reality Modeling Language
W3C:: World Wide Web Consortium
W3DS:: OGC Web 3D Service
WFS:: OGC Web Feature Service
X3D:: Open Standards XML-enabled 3D file format of the Web 3D Consortium
XML:: Extensible Markup Language
xAL:: OASIS extensible Address Language
