
[[conformance-section]]
== 一致性

这个标准定义了一个概念模型，它独立于任何编码或格式化技术。该标准的标准化目标包括：

. 概念模型 (此概念模型的详细版本)
. 实施规范 (此概念模型的编码)

[[conceptual-model-conformance]]
=== 概念模型

一个概念模型的标准化目标是为特定用户群体定制的CityGML 3.0概念模型（CM）版本。这种定制可以包括：

. 省略一个或多个可选的 UML 包；
. 减少属性或关联的多重性；
. 限制属性的有效值；
. 通过ADEs记录的额外概念。

在这些选项中，操作#1、#2和#3可以在创建实施规范时执行。只有操作#4需要扩展CityGML概念模型。
这些扩展通过在《应用领域扩展（ADE）》部分（<<rc_ade_section>>）中描述的ADE机制实现。

CityGML概念模型的扩展符合ADE一致性类的要求。

[[implementation-specification-conformance]]
=== 实施规范

实施规范定义了如何使用特定技术实施概念模型。符合规范的实施规范需要提供证据，证明其准确地表示了概念模型。这些证据应包括在本文档的 <<abstract-test-suite>> 部分中所指定的抽象测试的实现。

由于本标准与具体的实现技术无关，因此无法指定用于一致性测试的具体技术。实施规范需要提供适用于所使用实现技术的符合性证据。该证据应作为附录附加在实施规范文档中。

[[conformance-class-section]]
=== 一致性类

本标准定义了17个一致性性类。每个UML模型包都定义了一个一致性类。每个一致性类由一个要求类定义。<<abstract-test-suite>>中的测试按照要求类进行组织。
因此， __Core__ 一致性类的实现必须通过<<abstract-test-suite>>中 __Core__ 要求类指定的所有测试。

在这十七个符合性类别中，只有 __Core__ 一致性类是强制性的，所有其他一致性类都是可选的。如果某个一致性类依赖于另一个一致性类，则该一致性类也应该被实现。

CityGML概念模型由CityGML UML模型定义，本标准是UML模型的文档形式表示。如果UML模型与本文档存在不一致之处，以UML模型为准。
