[[conformance-section]]

== Conformance

This standard defines a <<conceptual_model_definition,Conceptual Model>> which is independent of any encoding or formatting techniques. The <<standardization-target-definition,Standardization Targets>> for this standard are:

. <<conceptual-model-definition,Conceptual Models>> (extended versions of this conceptual model)
. <<implementation-specification-definition,Implementation Specifications>> (encodings of this conceptual model)

[[conceptual-model-conformance]]
=== Conceptual Models

A Conceptual Model standardization target is a version of the CityGML 3.0 Conceptual Model (CM) tailored for a specific user community. This tailoring can include:

. Omission of one or more of the optional UML packages
. Reduction of the multiplicity for an attribute or association
. Restriction on the valid values for an attribute
. Additional concepts documented through ADEs.

Of these options, actions #1, #2, and #3 can be performed when creating an implementation specification. Only action #4 requires an extension of the CityGML conceptual model. These extensions are accomplished using the ADE mechanism described in <<rc_ade_section,Section 10>> Application Domain Extensions (ADE).

Extensions of the CityGML Conceptual Model conform with the ADE Conformance Class.

[[implementation-specification-conformance]]
=== Implementation Specifications

Implementation Specifications define how a Conceptual Model should be implemented using a specific technology. Conformant Implementation Specifications provide evidence that they are an accurate representation of the Conceptual Model. This evidence should include implementations of the abstract tests specified in <<abstract-test-suite,Annex A>> (normative) of this document.

Since this standard is agnostic to the implementing technologies, the specific techniques to be used for conformance testing cannot be specified. Implementation Specifications need to provide evidence of conformance which is appropriate for the implementing technologies. This evidence should be provided as an annex to the Implementation Specification document.

[[conformance-class-section]]
=== Conformance Classes

This standard identifies seventeen (17) conformance classes. One conformance class is defined for each package in the UML model. Each conformance class is defined by one requirements class. The tests in <<abstract-test-suite,Annex A>> are organized by Requirements Class. So an implementation of the _Core_ conformance class must pass all tests specified in Annex A for the _Core_ requirements class.

Of these seventeen conformance classes, only the _Core_ conformance class is mandatory. All other conformance classes are optional. In the case where a conformance class has a dependency on another conformance class, that conformance class should also be implemented.

The CityGML Conceptual Model is defined by the CityGML UML model. This standard is a representation of that UML model in document form. In the case of a discrepancy between the UML model and this document, the UML model takes precedence.
