
== Terms, definitions, symbols and abbreviated terms

This document used the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

=== Terms and definitions

==== 2D data

geometry of features is represented in a two-dimensional space

NOTE: In other words, the geometry of 2D data is given using (X,Y) coordinates.

[.source]
<<inspirebu,clause="definition 1">>

==== 2.5D data

geometry of features is represented in a three-dimensional space with the constraint that, for each (X,Y) position, there is only one Z

[.source]
<<inspirebu,clause="definition 2">>

==== 3D data

Geometry of features is represented in a three-dimensional space.

[.source]
<<inspirebu,clause="definition 3">>

==== application schema

A set of {{conceptual schema}} for data required by one or more applications. An application schema contains selected parts of the base schemas presented in the ORM Information Viewpoint. Designers of application schemas may extend or restrict the types defined in the base schemas to define appropriate types for an application domain. Application schemas are information models for a specific information community.

[.source]
<<OGCDR>>, http://www.opengis.net/def/glossary/term/ApplicationSchema

[[codelist-definition]]
==== codelist

A value domain including a code for each permissible value.

==== conceptual model

model that defines concepts of a universe of discourse

[.source]
<<iso19101-1,clause=4.1.5>>

==== conceptual schema

formal description of a {{conceptual model}}

[.source]
<<iso19101-1,clause=4.1.6>>

// TODO: enable second definition
// . base schema. Formal description of the model of any geospatial information. term:[application schema,Application schemas] are built from conceptual schemas.
//
// [.source]
// <<OGCDR>>, http://www.opengis.net/def/glossary/term/ConceptualSchema

==== Implementation Specification

Specified on the OGC Document Types Register

[.source]
<<OGCDTR>>, http://www.opengis.net/def/doc-type/is

==== levels of detail

quantity of information that portrays the real world

NOTE: The concept comprises data capturing rules of spatial object types, the accuracy and the types of geometries, and other aspects of a data specification. In particular, it is related to the notions of scale and resolution.

[.source]
<<inspire_glossary>>

==== life-cycle information

set of properties of a spatial object that describe the temporal characteristics of a version of a spatial object or the changes between versions

[.source]
<<inspire_glossary>>

==== Platform (Model Driven Architecture)

the set of resources on which a system is realized.

[.source]
<<OMGMDA>>

==== Platform Independent Model

a model that is independent of a specific platform

[.source]
<<OMGMDA>>

==== Platform Specific Model

a model of a system that is defined in terms of a specific platform

[.source]
<<OMGMDA>>


=== Abbreviated terms

2D:: Two Dimensional
3D:: Three Dimensional
AEC:: Architecture, Engineering, Construction
ALKIS:: German National Standard for Cadastral Information
ATKIS:: German National Standard for Topographic and Cartographic Information
BIM:: Building Information Modeling
B-Rep:: Boundary Representation
bSI:: buildingSMART International
CAD:: Computer Aided Design
COLLADA:: Collaborative Design Activity
CSG:: Constructive Solid Geometry
DTM:: Digital Terrain Model
DXF:: Drawing Exchange Format
EuroSDR:: European Spatial Data Research Organisation
ESRI:: Environmental Systems Research Institute
FM:: Facility Management
GDF:: Geographic Data Files
GDI-DE:: Spatial Data Infrastructure Germany (Geodateninfrastruktur Deutschland)
GDI:: NRW Geodata Infrastructure North-Rhine Westphalia
GML:: Geography Markup Language
IAI:: International Alliance for Interoperability (now buildingSMART International (bSI))
IETF:: Internet Engineering Task Force
IFC:: Industry Foundation Classes
IoT:: Internet of Things
ISO:: International Organization for Standardisation
ISO/TC211:: ISO Technical Committee 211
LOD:: Levels of Detail
MQTT:: Message Queuing Telemetry Transport
NBIMS:: National Building Information Model Standard
OASIS:: Organisation for the Advancement of Structured Information Standards
OGC:: Open Geospatial Consortium
OSCRE:: Open Standards Consortium for Real Estate
SIG:: Special Interest Group 3D of the GDI-DE
TIC:: Terrain Intersection Curve
TIN:: Triangulated Irregular Network
UML:: Unified Modeling Language
URI:: Uniform Resource Identifier
VRML:: Virtual Reality Modeling Language
W3C:: World Wide Web Consortium
W3DS:: OGC Web 3D Service
WFS:: OGC Web Feature Service
X3D:: Open Standards XML-enabled 3D file format of the Web 3D Consortium
XML:: Extensible Markup Language
xAL:: OASIS extensible Address Language
