[[ats_cityfurniture_classes]]
[abstract_test,label="/ats/cityfurniture/classes",subject='<<req_cityfurniture_classes,/req/cityfurniture/classes>>']
====
[.component,class=test-purpose]
--
To validate that the Implementation Specification correctly implements the UML Classes defined in the Conceptual Model.
--

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====

[.component,class=step]
======
For each UML class defined or referenced in the CityFurniture Package:

[.component,class=step]
--
Validate that the Implementation Specification contains a data element which represents the same concept as that defined for the UML class.
--

[.component,class=step]
--
Validate that the data element has the same relationships with other elements as those defined for the UML class. Validate that those relationships have the same source, target, direction, roles, and multiplicies as those documented in the Conceptual Model.
--

[.component,class=step]
--
Validate that the data element has the same properties (attributes) as those specified for the UML class. Validate that those properties have the same name, definition, type, and multiplicity of those documented in the Conceptual Model.
--

[.component,class=step]
--
Validate that the properties of the data element include those of all superclasses of the UML class as documented in the Conceptual Model. Validate that those properties have the same name, definition, type, and multiplicity of those documented in the Conceptual Model
--

[.component,class=step]
--
Validate that the associations represented for the data element include those of all superclasses of the UML class as documented in the Conceptual Model. Validate that those representations have the same source, target, roles, and multiplicity of those documented in the Conceptual Model
--

[.component,class=step]
--
Validate that the Implementation Specification enforces all constraints imposed on the UML class by the Conceptual Model
--
======
=====
====
